// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3LJ8AhF83vT63gFQNLr8ddEDnABL3k_s',
    appId: '1:538533138606:web:c16c59736758c47a9d1d3f',
    messagingSenderId: '538533138606',
    projectId: 'rehber-e25a5',
    authDomain: 'rehber-e25a5.firebaseapp.com',
    storageBucket: 'rehber-e25a5.appspot.com',
    measurementId: 'G-1QVMWN62FF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsgI_hEiOsyBctBP4Bc8qCI2LNnTiWAH4',
    appId: '1:538533138606:android:ac170fc53837c5919d1d3f',
    messagingSenderId: '538533138606',
    projectId: 'rehber-e25a5',
    storageBucket: 'rehber-e25a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtXRTzR13xdP_tONcGuA4DO8d7Nr8uKw8',
    appId: '1:538533138606:ios:a133b891e0e647f69d1d3f',
    messagingSenderId: '538533138606',
    projectId: 'rehber-e25a5',
    storageBucket: 'rehber-e25a5.appspot.com',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtXRTzR13xdP_tONcGuA4DO8d7Nr8uKw8',
    appId: '1:538533138606:ios:1a388c2bc5d764d29d1d3f',
    messagingSenderId: '538533138606',
    projectId: 'rehber-e25a5',
    storageBucket: 'rehber-e25a5.appspot.com',
    iosBundleId: 'com.example.travelApp.RunnerTests',
  );
}
